<a href="https://colab.research.google.com/github/MuhammadSarimUmer/Python-Learning/blob/master/Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np

NUMPY

In [60]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [61]:
zeroes = np.zeros((2,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [62]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [64]:
arranged = np.arange(0,12,2)
print(arranged)

[ 0  2  4  6  8 10]


In [65]:
distributed = np.linspace(0,1,5)
print(distributed)

[0.   0.25 0.5  0.75 1.  ]


In [66]:
float_arr = np.array([1,2,3],dtype = float)
print(float_arr)

[1. 2. 3.]


In [67]:
diagonal_matrix = np.eye(3)
print(diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
diagonal_custom = np.diag([1,2,3])
print(diagonal_custom)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [69]:
rng = np.random.default_rng(seed = 42)
print(rng.integers(0,54,size=10000))

[ 4 41 35 ... 19 30 33]


PANDAS


In [70]:
import pandas as pd

In [71]:
s = pd.Series([1,2,3,3,3,4], index = ['a','b','c','d','e','f'])
s

,0
a,1
b,2
c,3
d,3
e,3
f,4


In [72]:
print(s.values)
print(s.index)
print(s.dtype)

[1 2 3 3 3 4]
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')
int64


In [73]:
print(s.head)
print(s.tail)

<bound method NDFrame.head of a    1
b    2
c    3
d    3
e    3
f    4
dtype: int64>
<bound method NDFrame.tail of a    1
b    2
c    3
d    3
e    3
f    4
dtype: int64>


In [74]:
print(s.value_counts)

<bound method IndexOpsMixin.value_counts of a    1
b    2
c    3
d    3
e    3
f    4
dtype: int64>


In [75]:
data = {
    'name': ['sarim','umer'],
    'age': [20,18],
    'city':['karachi','quetta']
}
# df = pd.DataFrame(data)
# df

In [76]:
df = pd.read_csv('retail_sales_dataset.csv',parse_dates=['Date'],dtype={
    'Gender': 'category',
    'Product Category':'category'

})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Transaction ID    1000 non-null   int64         
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object        
 3   Gender            1000 non-null   category      
 4   Age               1000 non-null   int64         
 5   Product Category  1000 non-null   category      
 6   Quantity          1000 non-null   int64         
 7   Price per Unit    1000 non-null   int64         
 8   Total Amount      1000 non-null   int64         
dtypes: category(2), datetime64[ns](1), int64(5), object(1)
memory usage: 56.9+ KB


In [77]:
print('shape of data is: ',df.shape)
print('data types are: ',df.dtypes)

shape of data is:  (1000, 9)
data types are:  Transaction ID               int64
Date                datetime64[ns]
Customer ID                 object
Gender                    category
Age                          int64
Product Category          category
Quantity                     int64
Price per Unit               int64
Total Amount                 int64
dtype: object


In [78]:
print('Statistical analysis \n',df.describe())

Statistical analysis 
        Transaction ID                           Date         Age     Quantity  \
count     1000.000000                           1000  1000.00000  1000.000000   
mean       500.500000  2023-07-03 00:25:55.200000256    41.39200     2.514000   
min          1.000000            2023-01-01 00:00:00    18.00000     1.000000   
25%        250.750000            2023-04-08 00:00:00    29.00000     1.000000   
50%        500.500000            2023-06-29 12:00:00    42.00000     3.000000   
75%        750.250000            2023-10-04 00:00:00    53.00000     4.000000   
max       1000.000000            2024-01-01 00:00:00    64.00000     4.000000   
std        288.819436                            NaN    13.68143     1.132734   

       Price per Unit  Total Amount  
count     1000.000000   1000.000000  
mean       179.890000    456.000000  
min         25.000000     25.000000  
25%         30.000000     60.000000  
50%         50.000000    135.000000  
75%        300.0000

In [79]:
subset = df.loc[1:50,['Age']]
print(subset.head())

   Age
1   26
2   50
3   37
4   30
5   45


In [80]:
subset2 = df.iloc[1:50,1:6]
print(subset2.head())

        Date Customer ID  Gender  Age Product Category
1 2023-02-27     CUST002  Female   26         Clothing
2 2023-01-13     CUST003    Male   50      Electronics
3 2023-05-21     CUST004    Male   37         Clothing
4 2023-05-06     CUST005    Male   30           Beauty
5 2023-04-25     CUST006  Female   45           Beauty


In [81]:
high_data = df[(df['Price per Unit']>20) & (df['Total Amount']>200)]
print(high_data.head(15))



    Transaction ID       Date Customer ID  Gender  Age Product Category  \
1                2 2023-02-27     CUST002  Female   26         Clothing   
3                4 2023-05-21     CUST004    Male   37         Clothing   
8                9 2023-12-13     CUST009    Male   63      Electronics   
12              13 2023-08-05     CUST013    Male   22      Electronics   
14              15 2023-01-16     CUST015  Female   42      Electronics   
15              16 2023-02-17     CUST016    Male   19         Clothing   
19              20 2023-11-05     CUST020    Male   22         Clothing   
20              21 2023-01-14     CUST021  Female   50           Beauty   
23              24 2023-11-29     CUST024  Female   49         Clothing   
25              26 2023-10-07     CUST026  Female   28      Electronics   
27              28 2023-04-23     CUST028  Female   43           Beauty   
29              30 2023-10-29     CUST030  Female   39           Beauty   
30              31 2023-0

In [82]:
df.loc[df['Gender']=="Female",'Price per Unit'] += 25

In [83]:
# data = {
#     'name': ['sarim','umer','Akmal','Chandio'],
#     'age': [20,18,32,35],
#     'city':['karachi','quetta','lahore','karachi'],
#     'salary': [20000,90000,45000,35000]
# }
# df = pd.DataFrame(data)
# df.describe()
