<a href="https://colab.research.google.com/github/MuhammadSarimUmer/Python-Learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np
import time

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(np.eye(3))

(2, 3)
2
int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
arr = np.array([[1,2,3],
                [0,9,2],
                [7,1,12]])

print(arr.shape)

(3, 3)
